DELETE FROM [dbo].[tlkpPokeball]

INSERT INTO [dbo].[tlkpPokeball] VALUES
	(1, 'Poké Ball','https://www.clipartmax.com/png/full/145-1450297_pokeball-png-pikachu-pokeball.png'),
	(2, 'Great Ball', 'https://cdn2.bulbagarden.net/upload/b/bf/Dream_Great_Ball_Sprite.png'),
	(3, 'Ultra Ball', 'https://cdn2.bulbagarden.net/upload/a/a8/Dream_Ultra_Ball_Sprite.png'),
	(4, 'Master Ball', 'https://www.clipartmax.com/png/full/249-2496077_pokeball-png-download-pokemon-master-ball-png.png'),
	(5, 'Safari Ball', 'https://cdn2.bulbagarden.net/upload/1/15/Dream_Safari_Ball_Sprite.png'),
	(6, 'Fast Ball', 'https://cdn2.bulbagarden.net/upload/4/44/Dream_Fast_Ball_Sprite.png'),
	(7, 'Level Ball', 'https://cdn2.bulbagarden.net/upload/1/19/Dream_Level_Ball_Sprite.png'),
	(8, 'Lure Ball', 'https://cdn2.bulbagarden.net/upload/b/bd/Dream_Lure_Ball_Sprite.png'),
	(9, 'Heavy Ball', 'https://static1-us.millenium.gg/articles/5/10/09/5/@/117168-masse-full-1.png'),
	(10, 'Love Ball', 'https://www.clipartmax.com/png/full/129-1298488_love-ball-by-oykawoo-pokemon-love-ball-png.png'),
	(11, 'Friend Ball', 'https://cdn2.bulbagarden.net/upload/7/7a/Dream_Friend_Ball_Sprite.png'),
	(12, 'Moon Ball', 'https://cdn2.bulbagarden.net/upload/2/22/Dream_Moon_Ball_Sprite.png'),
	(13, 'Sport Ball', 'https://cdn2.bulbagarden.net/upload/d/df/Dream_Sport_Ball_Sprite.png'),
	(14, 'Net Ball', 'https://cdn2.bulbagarden.net/upload/a/a0/Dream_Net_Ball_Sprite.png'),
	(15, 'Nest Ball', 'https://cdn2.bulbagarden.net/upload/8/8c/Dream_Nest_Ball_Sprite.png'),
	(16, 'Repeat Ball', 'https://cdn10.bigcommerce.com/s-rdexxk0h/products/1108/images/1745/REPEAT__21052.1471758785.1000.1200.png?c=2'),
	(17, 'Timer Ball', 'https://www.clipartmax.com/png/full/44-443765_user-flame-alex-timer-ball-pokemon.png'),
	(18, 'Luxury Ball', 'https://cdn2.bulbagarden.net/upload/7/7e/Dream_Luxury_Ball_Sprite.png'),
	(19, 'Premier Ball', 'https://cdn2.bulbagarden.net/upload/6/64/Dream_Premier_Ball_Sprite.png'),
	(20, 'Dive Ball', 'https://www.clipartmax.com/png/full/190-1909064_buceo-ball-by-adfpf1-underwater-diving.png'),
	(21, 'Dusk Ball', 'https://cdn2.bulbagarden.net/upload/5/59/Dream_Dusk_Ball_Sprite.png'),
	(22, 'Heal Ball', 'https://www.clipartmax.com/png/full/44-444215_sugimorihealball-pokemon-heal-ball-png.png'),
	(23, 'Quick Ball', 'https://www.clipartmax.com/png/full/190-1908931_current-current-pokemon-quick-ball.png'),
	(24, 'Cherish Ball', 'https://www.freeiconspng.com/uploads/cherish-ball-png-14.png'),
	(25, 'Park Ball', 'https://cdn2.bulbagarden.net/upload/0/09/Dream_Park_Ball_Sprite.png'),
	(26, 'Dream Ball', 'https://cdn2.bulbagarden.net/upload/2/27/Dream_Dream_Ball_Sprite.png'),
	(27, 'Beast Ball', 'https://cdn2.bulbagarden.net/upload/6/65/Dream_Beast_Ball_Sprite.png');